### ISSUE TITLE
emty json form field after validation error

### ISSUE THREAD

**Issue by ChrisChrisi** [paulzi/yii2-json-behavior#10]
hi 

I have problem with the JsonValidator.
The problem and my used code are described below: 

I have activeRecord with a json_field property.  The json_field is a json column in postgres table. 
I have default generated crud with the default gii. 
When I try to submin the crete / update form with invalid json : 
![1](https://user-images.githubusercontent.com/5849357/37719692-3b0147e6-2d2e-11e8-93c1-eb9dfb00263c.png)

After validating the form the field is emptied:
![2](https://user-images.githubusercontent.com/5849357/37719845-aafdd3ac-2d2e-11e8-95bc-484ef3a5b9c9.png)
 
and the error message is "Syntax error." ,  not "Value is not valid JSON or scalar" like in the exaple in the readme file.

**The problem is:**
**- I want the field value to remain the samе, not being emptied after validation fail**  (so that the user will be able to fix the field value, not retyping it from the beginning )
**- How can I change the error message from  "Syntax error."  to a custom one ?**

The code in the  model is: 
```
namespace app\models;

use Yii;
use paulzi\jsonBehavior\JsonBehavior;
use paulzi\jsonBehavior\JsonValidator;

class Item extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms.item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 100],
            [['json_field'], JsonValidator::className(), 'skipOnEmpty' => true ],
        ];
    }

    public function behaviors() {
        return [
            [
                'class' => JsonBehavior::className(),
                'attributes' => ['json_field'],
            ],
        ];
    }
}
```
Thank, you for your attention

**Comment by paulzi** [comment]
> How can I change the error message from "Syntax error." to a custom one ?

You can configure error messages in version since 1.0.6.

> I want the field value to remain the samе, not being emptied after validation fail (so that the user will 
be able to fix the field value, not retyping it from the beginning )

It impossible in JsonBehavior because throughout the life cycle of the model with behavior, the JsonField is stored in the json attribute. After the validation, there must also be an instance of the class in this field, but it is impossible to do this because of a validation error, so it is reset.
https://github.com/paulzi/yii2-json-behavior/blob/master/src/JsonValidator.php#L39
