### ISSUE TITLE
saved as non json

### ISSUE THREAD

**Issue by vladimirovii** [paulzi/yii2-json-behavior#12]
PostgreSQL 9.5.13
select meta->>'metatitle' from table
return null

if this code
```
protected function encode()
    {
        foreach ($this->attributes as $attribute) {
            $field = $this->owner->getAttribute($attribute);
            if (!$field instanceof JsonField) {
                $field = new JsonField($field);
            }
            $this->owner->setAttribute($attribute, (string)$field ?: $this->emptyValue);
        }
    }
```
write to
`$this->owner->setAttribute($attribute, $field ?: $this->emptyValue);`

all okey

**Comment by paulzi** [comment]
Please provide more detailed information. What do you save and how?

**Comment by vladimirovii** [comment]
if i use your behavior
![screenshot from 2018-08-06 14-16-44](https://user-images.githubusercontent.com/11423651/43702353-bd85bf78-9983-11e8-8afc-d72e17fe4df9.png)
![screenshot from 2018-08-06 14-17-29](https://user-images.githubusercontent.com/11423651/43702361-c0c1ee82-9983-11e8-961a-d87a2e49f28a.png)

if i extends you behavior and rewrite encode to 
`$this->owner->setAttribute($attribute, $field ?: $this->emptyValue);`
![screenshot from 2018-08-06 14-18-01](https://user-images.githubusercontent.com/11423651/43702397-e1fffc2e-9983-11e8-8a9a-ed3e4aef1f95.png)
![screenshot from 2018-08-06 14-18-16](https://user-images.githubusercontent.com/11423651/43702399-e51b3914-9983-11e8-82f0-55c561bffdfd.png)

**Comment by paulzi** [comment]
Do you use version Yii >= 2.0.14?
In version 2.0.14, the Yii contains a built-in JSON type, and this behavior is no longer required. And moreover, it is not compatible with this version of framework (BC break).

**Comment by vladimirovii** [comment]
yes Yii >= 2.0.14
graet, thank you
sorry
