### ISSUE TITLE
Добавить возможность сохранять в базу как db\JsonExpression

### ISSUE THREAD

**Issue by AlexBad** [paulzi/yii2-json-behavior#13]
Приветствую.

Предлагаю добавить функционал позволяющий выполнять сохранение в базу как
\yii\db\JsonExpression.

В файлик, paulzi\jsonBehavior\JsonBehavior добавить:
```php
/**
* @var bool
*/
public $asJsonExpression = false;
```

И в методе `encode()` добавить следующее:
```php
/**
*/
protected function encode()
{
    if ($this->asJsonExpression) {
        $this->owner->attributes = new \yii\db\JsonExpression($this->attributes);
    } else {
        foreach ($this->attributes as $attribute) {
            $field = $this->owner->getAttribute($attribute);
            if (!$field instanceof JsonField) {
                $field = new JsonField($field);
            }
            $this->owner->setAttribute($attribute, (string)$field ?: $this->emptyValue);
        }
    }   
}
```

**Comment by paulzi** [comment]
Тут наверное всё-таки нужен цикл и каждый атрибут сделать JsonExpression?
```php
if ($this->asJsonExpression) {
    $this->owner->attributes = new \yii\db\JsonExpression($this->attributes);
}
```

И не очень понятно для чего это делать? Начиная с версии Yii 2.0.14 фреймворк сам умеет делать encode/decode полей БД имеющих тип JSON. Для них behavior этот не нужен.

**Comment by AlexBad** [comment]
У меня последняя версия на текущий момент. И в базу сохраняется, как строка со слэшами
Собственно, пропадает функционал поиска по JSON полю в самой базе.
```php
$model->jsonField = [
  'id' => 123, 'name' => 'Default Name'
];
```
В саму базу пишется, как ```"{\"id\": \"123\", \"name\":\"Default Name\"}"```
При этом, если писать как JsonExpression, то в базу попадает в корректном виде, если база поддерживает поле Json, либо, как строка с обратными слэшами, если Json строка не поддерживается.
```php
$model->jsonField = new \yii\db\JsonExpression([
  'id' => 123, 'name' => 'Default Name'
]);
```
На выходе получаем, ```{"id": 123, "name": "Default Name"}```, то что нужно.

Также, я делаю пустую "Виртуальную модель", описываю ее, валидирую, и только после загоняю атрибуты "Виртуальной модели" в JSON поле
```php
class VirtualJsonField extends \yii\base\Model
{
  public $id;
  public $name;
  ...
}
// В самой модели:
$model->jsonField = $virtualJsonField->attributes;
```
поэтому, правило имеет смысл указывать для всех виртуальных полей...

наверняка можно сделать более элегантно, но видимо мне не хватает фантазии\скила :)

В любом случаи, я сделал свое поведение которое расширяет твое и добавляет нужный мне функционал.

**Comment by paulzi** [comment]
Какую вы базу используете и какой тип поля?
Если добавляются слэши - значит в БД передаётся JSON как строка, а не как выражение.

**Comment by AlexBad** [comment]
> Какую вы базу используете и какой тип поля?

MySQL 5.7.26 (Windows), JSON type
> Если добавляются слэши - значит в БД передаётся JSON как строка, а не как выражение.

Совершенно верно. И вот чтобы напрямую сказать, что должно передаваться ворожение я и сделал "принудительную" запись как выражение.

А вот почему Yii не определяет что это Json, я не совсем понимаю :)

**Comment by paulzi** [comment]
В общем проверил, версии такие:
yii2 2.0.34
php 7.2
mysql 8.0.13

Если сделать тип поля json, и подключить этот behavior, сохраняется действительно с экранированием, и это не удивительно, т. к. JsonBehavior преобразует значение в строку перед сохранением в БД, а yiiшка автоматом превращает значение в JsonExpression("строка"), отсюда и экранирование.
Но как я и писал, начиная с 2.0.14 behavior не нужно подключать для нативных json полей, всё это уже делает сама Yiiшка.

Вот пример:
Схема:
```php
$this->createTable('{{%item}}', [
    'id'     => $this->primaryKey(),
    'params' => $this->json(),
]);
```

Модель (вообще голая получилась):
```php
class Item extends ActiveRecord
{
}
```

Тестируем:
```php
$item = new Item();
$item->params = [
    'one' => 'value',
    'two' => [
        'test' => true,
    ],
];
$item->save(false);
$item->params = ['one' => 42] + $item->params;
var_dump($item->params['one'] === 42); // true

$item = Item::findOne($item->id);
var_dump($item->params['one'] === 'value'); // true
var_dump($item->params['two']['test'] === true); // true
```

Единственное неудобство - это ошибка "Indirect modification of overloaded property" при попытке прямой модификации массива внутри json:
```php
$item->params['one'] = 42; // throw Indirect modification of overloaded property
```
Но ради этого применять behavior считаю неоправданным.
