### ISSUE TITLE
Missing event listener for AR::refresh()

### ISSUE THREAD

**Issue by haolian9** [paulzi/yii2-json-behavior#3]
Sometimes We will use AR::refresh(), but there is only event invoked by this method: AR::afterRefresh().

**Comment by paulzi** [comment]
The listener afterRefresh is not required, because the attribute is copied after decode:
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1015

**Comment by haolian9** [comment]
Yes, I was wrong, and thnks you.
