### ISSUE TITLE
Existing values merging

### ISSUE THREAD

**Issue by wa1kb0y** [paulzi/yii2-json-behavior#4]
Thank you for great extension.
One question, is possible to update field with merging existing values?
Currently i solve it in my model like this:
```
private $_temp_params;

public function afterFind()
{
    parent::afterFind();
    $this->_temp_params = $this->params->toArray();
}

public function beforeSave($insert)
{
    $this->params = array_merge($this->_temp_params, $this->params->toArray());
    if (parent::beforeSave($insert)) {
        return true;
    }
    return false;
}
```

Would be great to add some flag in behavior's settings.

**Comment by paulzi** [comment]
Why you are not set params directly?
```php
public function actionUpdate($id)
{
    $model = $this->findModel($id);
    $model->params->someParameter['value'] = 'test';
    $model->save();
}
```

**Comment by wa1kb0y** [comment]
I have a lot of parameters, some for one record, some for another. Some of them could be declared, but some are not. Model is updated in different methods. I just need the opportunity not to lose them when updating the model. 
I have already solved my problem, but still the following behavior seems to me strange.
For example:
```php
$model->params['test1'] = '123';
$model->params['test2'] = '456';
$model->save(); //test=>123, test2=>456 (ok)

$model->params['test2'] = '789';
$model->save(); //test2=>789 ("test1" is removed now)
```

**Comment by paulzi** [comment]
You are wrong, the `test1` key should be saved, and should not be deleted.

I wrote a test that you can run and see for yourself, in the branch `issue4`:
https://github.com/paulzi/yii2-json-behavior/blob/37746bede7281157935249aca79de7d629eff21d/tests/BehaviorTest.php#L342-L350

**Comment by wa1kb0y** [comment]
Yes, u right, test is correct.
Seems issue arise only in forms:
```php
<?= $form->field($model, 'param[test1]')->textInput() ?>
```
This code will rewrite all existing and write `test1` only
Maybe problem in model load function in Controller:
```php
if ($model->load(Yii::$app->request->post()) && $model->save()) {
}
```

**Comment by paulzi** [comment]
I understood what your problem is in that `->load()` overwrites the params completely, because the validator is triggered. The validator takes the data from POST and overwrite completely new data to the params. In order for this to happen, you can transfer the necessary parameters in hidden fields.

I will do an option for the validator, so that he does the merge, instead of replacing data.
